<?php
/**
 * RooCMS - Open Source Free Content Managment System
 * © 2010-2025 alexandr Belov aka alex Roosso. All rights reserved.
 * @author    alex Roosso <info@roocms.com>
 * @link      https://www.roocms.com
 * @license   https://www.gnu.org/licenses/gpl-3.0.html
 *
 * You should have received a copy of the GNU General Public License v3
 * along with this program. If not, see https://www.gnu.org/licenses/
 */

//#########################################################
//	Protect
//---------------------------------------------------------
if(!defined('RooCMS')) {roocms_protect();}
//#########################################################


/**
 * Migration Two Zero: Install data
 */
return [
	'up' => [
		'data' => [
			'TABLE_SETTINGS' => [
				[
					'category' => 'site',
					'sort_order' => 1,
					'title' => 'Site domain',
					'description' => 'Please specify without http:// or https://',
					'key' => 'site_domain',
					'type' => 'string',
					'options' => null,
					'value' => null,
					'default_value' => '',
					'max_length' => 255,
					'is_required' => 1,
					'is_serialized' => 0
				],
				[
					'category' => 'site',
					'sort_order' => 2,
					'title' => 'Site name',
					'description' => 'Global site name',
					'key' => 'site_name',
					'type' => 'string',
					'options' => null,
					'value' => null,
					'default_value' => 'RooCMS',
					'max_length' => 255,
					'is_required' => 1,
					'is_serialized' => 0
				],
				[
					'category' => 'site',
					'sort_order' => 3,
					'title' => 'Site description',
					'description' => 'Global site description',
					'key' => 'site_description',
					'type' => 'string',
					'options' => null,
					'value' => null,
					'default_value' => 'Open Source Content Management System',
					'max_length' => 255,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 1,
					'title' => 'Driver of sending mail',
					'description' => 'Method of sending mail',
					'key' => 'mailer_driver',
					'type' => 'select',
					'options' => '{"mail":"PHP mail()","smtp":"SMTP","sendmail":"sendmail"}',
					'value' => null,
					'default_value' => 'mail',
					'max_length' => 10,
					'is_required' => 1,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 2,
					'title' => 'SMTP host',
					'description' => 'This option is required for SMTP driver',
					'key' => 'mailer_host',
					'type' => 'string',
					'options' => null,
					'value' => null,
					'default_value' => 'localhost',
					'max_length' => 255,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 3,
					'title' => 'SMTP port',
					'description' => 'Usually 587 (TLS) or 465 (SSL)',
					'key' => 'mailer_port',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '25',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 4,
					'title' => 'SMTP login',
					'description' => 'This option is required for SMTP driver',
					'key' => 'mailer_username',
					'type' => 'string',
					'options' => null,
					'value' => null,
					'default_value' => '',
					'max_length' => 255,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 5,
					'title' => 'SMTP password',
					'description' => 'This option is required for SMTP driver',
					'key' => 'mailer_password',
					'type' => 'string',
					'options' => null,
					'value' => null,
					'default_value' => '',
					'max_length' => 255,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 6,
					'title' => 'Encryption',
					'description' => 'Choose the encryption level of your connection for sending emails: tls or ssl',
					'key' => 'mailer_encryption',
					'type' => 'select',
					'options' => '{"tls":"TLS (STARTTLS)","ssl":"SSL","none":"None"}',
					'value' => null,
					'default_value' => 'tls',
					'max_length' => 10,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 7,
					'title' => 'Email sender',
					'description' => 'Here should be the email of the sender of the emails',
					'key' => 'mailer_from',
					'type' => 'email',
					'options' => null,
					'value' => null,
					'default_value' => '',
					'max_length' => 255,
					'is_required' => 1,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 8,
					'title' => 'Sender name',
					'description' => 'Here should be the name of the sender of the emails',
					'key' => 'mailer_from_name',
					'type' => 'string',
					'options' => null,
					'value' => null,
					'default_value' => '',
					'max_length' => 255,
					'is_required' => 1,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 9,
					'title' => 'Reply-To email',
					'description' => 'Here should be the email of the sender of the answers to the emails',
					'key' => 'mailer_reply_to',
					'type' => 'email',
					'options' => null,
					'value' => null,
					'default_value' => '',
					'max_length' => 255,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 10,
					'title' => 'Reply-To name',
					'description' => 'Here should be the name of the sender of the answers to the emails',
					'key' => 'mailer_reply_to_name',
					'type' => 'string',
					'options' => null,
					'value' => null,
					'default_value' => '',
					'max_length' => 255,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 11,
					'title' => 'Max attachment size (bytes)',
					'description' => 'Default 10 MB. Maximum size of the attachments of the emails',
					'key' => 'mailer_max_attachment_size',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '10485760',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 12,
					'title' => 'Max attachments count',
					'description' => 'Default 10. Maximum count of the attachments of the emails',
					'key' => 'mailer_max_attachments_count',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '10',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 13,
					'title' => 'Check SSL certificate',
					'description' => 'Check SSL certificate for SMTP driver. This option is required for SMTP driver',
					'key' => 'mailer_verify_peer',
					'type' => 'boolean',
					'options' => null,
					'value' => null,
					'default_value' => '0',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 14,
					'title' => 'Check SSL certificate name',
					'description' => 'Check SSL certificate name for SMTP driver. If you have a self-signed certificate, you need to set this option to 1. This option is required for SMTP driver',
					'key' => 'mailer_verify_peer_name',
					'type' => 'boolean',
					'options' => null,
					'value' => null,
					'default_value' => '0',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 15,
					'title' => 'Allow self-signed certificates',
					'description' => 'Allow self signed for SMTP driver. If you have a self-signed certificate, you need to set this option to 1. This option is required for SMTP driver',
					'key' => 'mailer_allow_self_signed',
					'type' => 'boolean',
					'options' => null,
					'value' => null,
					'default_value' => '1',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'mailer',
					'sort_order' => 16,
					'title' => 'URI for verification email',
					'description' => 'URI for verification email. Use URI path without domain name. Example: /verify-email',
					'key' => 'mailer_verification_mail_uri',
					'type' => 'string',
					'options' => null,
					'value' => null,
					'default_value' => '/verify-email',
					'max_length' => 255,
					'is_required' => 1,
					'is_serialized' => 0
				],
				[
					'category' => 'security',
					'sort_order' => 1,
					'title' => 'Hash Key',
					'description' => 'Hash Key for token cryptography. This option is required for token cryptography',
					'key' => 'security_token_hash_key',
					'type' => 'string',
					'options' => null,
					'value' => null,
					'default_value' => 'RooCMS',
					'max_length' => 255,
					'is_required' => 1,
					'is_serialized' => 0
				],
				[
					'category' => 'security',
					'sort_order' => 2,
					'title' => 'Hash Cost',
					'description' => 'Hash Cost for token cryptography. 10 is good for most servers. If your server is powerful enough, you can set it to more. For calculating optimal cost, you can use CLI script pastcost.php.',
					'key' => 'security_token_hash_cost',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '10',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'security',
					'sort_order' => 3,
					'title' => 'Token Length',
					'description' => 'Token Length for token cryptography',
					'key' => 'security_token_length',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '32',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'security',
					'sort_order' => 4,
					'title' => 'Token expires',
					'description' => 'TTL to access token. Default 1 hour.',
					'key' => 'security_token_expires',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '3600',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'security',
					'sort_order' => 5,
					'title' => 'Refresh token expires',
					'description' => 'TTL to refresh token. Default 24 hours.',
					'key' => 'security_refresh_token_expires',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '86400',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'security',
					'sort_order' => 6,
					'title' => 'Minimal password length',
					'description' => 'Minimal password length. Default 8.',
					'key' => 'security_password_length',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '8',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 1,
					'title' => 'Thumbnail type',
					'description' => 'Thumbnail type generate. Overflow or contain. Default: overflow',
					'key' => 'gd_thumb_type_gen',
					'type' => 'select',
					'options' => '{"overflow":"cover","contain":"contain"}',
					'value' => null,
					'default_value' => 'overflow',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 2,
					'title' => 'Thumbnail background color',
					'description' => 'Thumbnail background color. Default: #ffffff (white)',
					'key' => 'gd_thumb_bgcolor',
					'type' => 'color',
					'options' => null,
					'value' => null,
					'default_value' => '#ffffff',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 3,
					'title' => 'Thumbnail quality',
					'description' => 'Thumbnail quality. Default: 90 percent',
					'key' => 'gd_thumb_jpg_quality',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '90',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 4,
					'title' => 'Thumbnail width',
					'description' => 'Thumbnail width. Default: 378 pixels',
					'key' => 'gd_thumb_image_width',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '378',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 5,
					'title' => 'Thumbnail height',
					'description' => 'Thumbnail height. Default: 212 pixels',
					'key' => 'gd_thumb_image_height',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '212',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 6,
					'title' => 'Max image width',
					'description' => 'Max image width. If image width is greater than this value, it will be resized to this value. Default: 1920 pixels',
					'key' => 'gd_image_maxwidth',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '1920',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 7,
					'title' => 'Max image height',
					'description' => 'Max image height. If image height is greater than this value, it will be resized to this value. Default: 1080 pixels',
					'key' => 'gd_image_maxheight',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '1080',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 8,
					'title' => 'Use watermark',
					'description' => 'Use watermark. Watermark is a text or image that is added to the image.',
					'key' => 'gd_use_watermark',
					'type' => 'boolean',
					'options' => null,
					'value' => null,
					'default_value' => '0',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 9,
					'title' => 'Watermark type',
					'description' => 'Watermark type. Image or text. Default: text',
					'key' => 'gd_watermark_type',
					'type' => 'select',
					'options' => '{"text":"Text","image":"Image"}',
					'value' => null,
					'default_value' => 'text',
					'max_length' => 255,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 10,
					'title' => 'Watermark image (png)',
					'description' => 'Watermark image. Recommended to use this parameter for better visualization. Recommended file format: png.',
					'key' => 'gd_watermark_image',
					'type' => 'image',
					'options' => null,
					'value' => null,
					'default_value' => null,
					'max_length' => 255,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 11,
					'title' => 'Watermark image position',
					'description' => 'Watermark image position. The position of the watermark image. Default: bottom right',
					'key' => 'gd_watermark_image_position',
					'type' => 'select',
					'options' => '{"top left":"top left","top center":"top center","top right":"top right","center left":"center left","center center":"center center","center right":"center right","bottom left":"bottom left","bottom center":"bottom center","bottom right":"bottom right"}',
					'value' => null,
					'default_value' => 'bottom right',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 12,
					'title' => 'Watermark image opacity',
					'description' => 'Watermark image opacity. Default: 50 percent',
					'key' => 'gd_watermark_image_opacity',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '50',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 13,
					'title' => 'Max Watermark image size relative to image',
					'description' => 'Watermark image size max relative to image. Default: 50 percent',
					'key' => 'gd_watermark_image_size',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '50',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 14,
					'title' => 'Watermark image x',
					'description' => 'Watermark image x. Default: 10 pixels',
					'key' => 'gd_watermark_image_x',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '10',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 15,
					'title' => 'Watermark image y',
					'description' => 'Watermark image y. Default: 10 pixels',
					'key' => 'gd_watermark_image_y',
					'type' => 'integer',
					'options' => null,
					'value' => null,
					'default_value' => '10',
					'max_length' => null,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 16,
					'title' => 'Watermark text string one',
					'description' => 'Watermark text string one.',
					'key' => 'gd_watermark_text_one',
					'type' => 'string',
					'options' => null,
					'value' => null,
					'default_value' => null,
					'max_length' => 255,
					'is_required' => 0,
					'is_serialized' => 0
				],
				[
					'category' => 'gd',
					'sort_order' => 17,
					'title' => 'Watermark text string two',
					'description' => 'Watermark text string two.',
					'key' => 'gd_watermark_text_two',
					'type' => 'string',
					'options' => null,
					'value' => null,
					'default_value' => null,
					'max_length' => 255,
					'is_required' => 0,
					'is_serialized' => 0
				],
			],
		],
	],

	'down' => [
		'delete_data' => [
			'TABLE_SETTINGS' => [
				'where_by_driver' => [
					'mysql' => '`key` IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
					'postgresql' => '"key" IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
					'firebird' => '"key" IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
				],
				'params' => [
					'site_domain',
					'site_name',
					'site_description',
					'mailer_driver',
					'mailer_host',
					'mailer_port',
					'mailer_username',
					'mailer_password',
					'mailer_encryption',
					'mailer_from',
					'mailer_from_name',
					'mailer_reply_to',
					'mailer_reply_to_name',
					'mailer_max_attachment_size',
					'mailer_max_attachments_count',
					'mailer_verify_peer',
					'mailer_verify_peer_name',
					'mailer_allow_self_signed',
					'mailer_verification_mail_uri',
					'security_token_hash_key',
					'security_token_hash_cost',
					'security_token_length',
					'security_token_expires',
					'security_refresh_token_expires',
					'security_password_length',
					'gd_thumb_type_gen',
					'gd_thumb_bgcolor',
					'gd_thumb_jpg_quality',
					'gd_thumb_image_width',
					'gd_thumb_image_height',
					'gd_image_maxwidth',
					'gd_image_maxheight',
					'gd_use_watermark',
					'gd_watermark_type',
					'gd_watermark_image',
					'gd_watermark_image_position',
					'gd_watermark_image_opacity',
					'gd_watermark_image_size',
					'gd_watermark_image_x',
					'gd_watermark_image_y',
					'gd_watermark_text_one',
					'gd_watermark_text_two'
				],
			],
		],
	],
];


